[workspace]
resolver = "2"
members = [
    "crates/emf-common",
    "crates/emf-ecore",
    "crates/emf-artop/autosar448-model",
    "crates/emf-ecore-util",
    "crates/emf-ecore-codegen",
    "crates/emf-xmi",
    "crates/emf-xsd",
    "crates/emf-edit",
    "crates/emf-compare",
    "crates/emf-validation",
    "crates/emf-xcore",
    "crates/emf-acceleo",
    "crates/emf-sphinx",
    "crates/emf-artop/artop-runtime",
    "crates/emf-artop/artop-codegen",
    "examples/arxml-roundtrip",
    "examples/arxml-validate",
]

[workspace.dependencies]
emf-common = { path = "crates/emf-common" }
emf-ecore = { path = "crates/emf-ecore" }
autosar448-model = { path = "crates/emf-artop/autosar448-model" }
emf-ecore-util = { path = "crates/emf-ecore-util" }
emf-ecore-codegen = { path = "crates/emf-ecore-codegen" }
emf-xmi = { path = "crates/emf-xmi" }
emf-xsd = { path = "crates/emf-xsd" }
emf-edit = { path = "crates/emf-edit" }
emf-compare = { path = "crates/emf-compare" }
emf-validation = { path = "crates/emf-validation" }
emf-xcore = { path = "crates/emf-xcore" }
emf-acceleo = { path = "crates/emf-acceleo" }
emf-sphinx = { path = "crates/emf-sphinx" }
artop-runtime = { path = "crates/emf-artop/artop-runtime" }
artop-codegen = { path = "crates/emf-artop/artop-codegen" }

[profile.release]
opt-level = 2