//! ARTOP static-model generator (port of C++ `ArtopCppGenerator`).
//!
//! `ArtopGenerator` inherits the generic [`emf_ecore_codegen`] pipeline (the C++
//! `CppGenerator` base) and appends the ARTOP-specific steps in the same order as
//! the C++ implementation:
//!
//!   * `generate_from_file` — C++ `generateFromFile`: load the `.ecore`, then run
//!     `generate_from_package` on it (the C++ base calls the 2-arg
//!     `generateFromPackage` non-virtually, so the ARTOP extensions are invoked
//!     explicitly here as well).
//!   * `generate_from_package` — C++ `generateFromPackage`: emit the base model
//!     crate, then the ARTOP extensions.
//!
//! The only deliberate adaptation is the target language: C++ emits one header per
//! class plus `<Pkg>ResourceImpl.h` / `<Pkg>ResourceFactoryImpl.h`; the Rust base
//! emits a single self-contained `src/lib.rs`, so the resource glue becomes the
//! `resource` / `resource_factory` modules of that crate and the root-extension
//! record stays `ARTOP_ROOT_EXTENSIONS.md` at the crate root.

use std::path::{Path, PathBuf};

use emf_ecore::EPackage;
use emf_ecore_codegen::typing::{package_module_name, struct_name};
use emf_ecore_codegen::{CrateSpec, GenModel};

/// ARTOP-specific generation configuration (C++ `ArtopGenConfig`).
#[derive(Debug, Clone)]
pub struct ArtopGenConfig {
    /// Input `.ecore` document (C++ `GenConfig::inputEcorePath`).
    pub input_ecore: PathBuf,
    /// Output directory — the generated crate's root (C++
    /// `GenConfig::outputDirectory`).
    pub out_dir: PathBuf,
    /// Rust crate build settings: crate name + runtime dependency roots.
    pub crate_spec: CrateSpec,
    /// Filesystem path to the `artop-runtime` crate, wired into the generated
    /// crate's manifest when the resource glue is emitted.
    pub artop_runtime: PathBuf,
    /// AUTOSAR release id (C++ default `org.artop.aal.autosar448`).
    pub release_id: String,
    /// AUTOSAR version, `major.minor.revision` (C++ default `4.4.8`).
    pub version: String,
    /// Base namespace URI (C++ default `http://autosar.org/schema/r4.0`).
    pub base_namespace_uri: String,
    /// Full `xsi:schemaLocation` value.
    pub schema_location: String,
    /// Emit the `<Pkg>Resource` / `<Pkg>ResourceFactory` glue.
    pub generate_resource: bool,
    /// Emit the `ARTOP_ROOT_EXTENSIONS.md` injection record.
    pub inject_root_extensions: bool,
}

impl Default for ArtopGenConfig {
    fn default() -> Self {
        let crate_spec = CrateSpec::default();
        // `CrateSpec::default` resolves the runtime deps as the sibling crates of
        // this one; `artop-runtime` is their `emf-artop` sibling.
        let artop_runtime = crate_spec
            .emf_common
            .parent()
            .map(|crates| crates.join("emf-artop").join("artop-runtime"))
            .unwrap_or_default();
        Self {
            input_ecore: PathBuf::new(),
            out_dir: PathBuf::new(),
            crate_spec,
            artop_runtime,
            release_id: "org.artop.aal.autosar448".to_string(),
            version: "4.4.8".to_string(),
            base_namespace_uri: "http://autosar.org/schema/r4.0".to_string(),
            schema_location: "http://autosar.org/schema/r4.0 AUTOSAR_4-4-8.xsd".to_string(),
            generate_resource: true,
            inject_root_extensions: true,
        }
    }
}

/// The ARTOP static-model generator (C++ `ArtopCppGenerator`).
#[derive(Debug, Default)]
pub struct ArtopGenerator {
    config: ArtopGenConfig,
    model: Option<GenModel>,
}

impl ArtopGenerator {
    /// Construct with a configuration (C++ `ArtopCppGenerator(ArtopGenConfig)`).
    pub fn new(config: ArtopGenConfig) -> Self {
        Self {
            config,
            model: None,
        }
    }

    /// The configuration in use.
    pub fn config(&self) -> &ArtopGenConfig {
        &self.config
    }

    /// The model generated by the last run, if any (C++ `package()`).
    pub fn model(&self) -> Option<&GenModel> {
        self.model.as_ref()
    }

    /// Load the configured `.ecore` and generate (C++ `generateFromFile`).
    pub fn generate_from_file(&mut self) -> Result<(), String> {
        let model = GenModel::load_path(&self.config.input_ecore)?;
        self.generate_from_package(&model)
    }

    /// Generate from an already loaded model (C++ `generateFromPackage`).
    ///
    /// Step 1 is the generic model crate; steps 2/3 are the ARTOP extensions.
    pub fn generate_from_package(&mut self, model: &GenModel) -> Result<(), String> {
        let pkg = model.package();
        let name = self.crate_name(model);
        let src_dir = self.config.out_dir.join("src");
        std::fs::create_dir_all(&src_dir)
            .map_err(|e| format!("creating `{}`: {e}", src_dir.display()))?;

        // 1. Base crate: manifest + one self-contained `lib.rs`. The resource
        //    glue's module declarations are appended so the crate wires them in.
        std::fs::write(self.config.out_dir.join("Cargo.toml"), self.manifest(&name))
            .map_err(|e| format!("writing manifest: {e}"))?;
        let mut lib = model.generate_source();
        if self.config.generate_resource {
            lib.push_str("\npub mod resource;\npub mod resource_factory;\n");
        }
        std::fs::write(src_dir.join("lib.rs"), lib).map_err(|e| format!("writing lib.rs: {e}"))?;

        // 2. ARTOP extensions.
        if self.config.generate_resource {
            self.generate_resource_and_factory(pkg, &src_dir)?;
        }
        if self.config.inject_root_extensions {
            self.generate_root_extensions(pkg)?;
        }

        self.model = Some(model.clone());
        Ok(())
    }

    /// Emit the `<Pkg>Resource` / `<Pkg>ResourceFactory` modules (C++
    /// `generateResourceAndFactory`).
    fn generate_resource_and_factory(
        &self,
        package: &EPackage,
        src_dir: &Path,
    ) -> Result<(), String> {
        let prefix = class_prefix(package.name());
        let snake = package_module_name(package.name());
        write_file(
            &src_dir.join("resource.rs"),
            &self.resource_module(&prefix, &snake),
        )?;
        write_file(
            &src_dir.join("resource_factory.rs"),
            &self.resource_factory_module(&prefix, &snake),
        )
    }

    /// Emit `ARTOP_ROOT_EXTENSIONS.md` (C++ `generateRootExtensions`).
    fn generate_root_extensions(&self, package: &EPackage) -> Result<(), String> {
        let mut out = String::new();
        out.push_str("# ARTOP Root Extensions Injection Plan\n\n");
        out.push_str(&format!("Package: {}\n", package.name()));
        out.push_str(&format!("Namespace: {}\n", self.config.base_namespace_uri));
        out.push_str(&format!(
            "SchemaLocation: {}\n\n",
            self.config.schema_location
        ));
        out.push_str("## Root EClass candidates for mixed/extensions injection\n\n");

        // C++ `generateRootExtensions` lists every non-abstract EClass (the root
        // EClass simplification documented in the C++ header).
        let mut count = 0;
        for class in package.classes() {
            if !class.is_abstract() {
                out.push_str(&format!("- {}\n", class.name()));
                count += 1;
            }
        }
        if count == 0 {
            out.push_str("(none)\n");
        }

        out.push_str(
            "\n## Injection details\n\n\
             Each root EClass will receive:\n\
             - `mixed` (EFeatureMap, many-valued) — captures unknown XML elements\n\
             - `extensions` (EFeatureMap, many-valued) — captures XML comments/PIs\n\n\
             Generated by ArtopGenerator\n",
        );
        write_file(&self.config.out_dir.join("ARTOP_ROOT_EXTENSIONS.md"), &out)
    }

    /// The generated `<Pkg>Resource` module (Rust analogue of the C++
    /// `<Pkg>ResourceImpl.h`).
    fn resource_module(&self, prefix: &str, snake: &str) -> String {
        format!(
            "//! <auto-generated/> {prefix} AUTOSAR XML resource.\n\
             //!\n\
             //! Port of the C++ `{prefix}ResourceImpl` (aligned to Java\n\
             //! `org.artop.aal.autosar448.{prefix}ResourceImpl`): a thin alias for the\n\
             //! runtime `AutosarXMLResource`, so the model crate exposes its own resource\n\
             //! type just like the C++ generator emits `{prefix}ResourceImpl.h`.\n\
             use artop_runtime::AutosarXMLResource;\n\
             use emf_common::uri::Uri;\n\
             use emf_ecore::PackageRegistry;\n\
             \n\
             /// `{prefix}` AUTOSAR XML resource.\n\
             pub type {prefix}Resource = AutosarXMLResource;\n\
             \n\
             /// Create a `{prefix}Resource` addressed by `uri` (the Rust analogue of the\n\
             /// C++ `{prefix}ResourceImpl(URI)` constructor).\n\
             pub fn new_{snake}_resource(uri: Uri, registry: PackageRegistry) -> {prefix}Resource {{\n\
             \x20   AutosarXMLResource::new(uri, registry)\n\
             }}\n"
        )
    }

    /// The generated `<Pkg>ResourceFactory` module (Rust analogue of the C++
    /// `<Pkg>ResourceFactoryImpl.h`).
    fn resource_factory_module(&self, prefix: &str, snake: &str) -> String {
        let release_id = &self.config.release_id;
        let version = &self.config.version;
        let namespace = &self.config.base_namespace_uri;
        let schema_location = &self.config.schema_location;
        format!(
            "//! <auto-generated/> {prefix} AUTOSAR resource factory.\n\
             //!\n\
             //! Port of the C++ `{prefix}ResourceFactoryImpl` (aligned to Java\n\
             //! `org.artop.aal.autosar448.{prefix}ResourceFactoryImpl`).\n\
             use artop_runtime::{{\n\
             \x20   AutosarMetaModelVersionData, AutosarReleaseDescriptor, AutosarResourceFactory,\n\
             }};\n\
             \n\
             /// AUTOSAR release id.\n\
             pub const RELEASE_ID: &str = \"{release_id}\";\n\
             /// AUTOSAR version.\n\
             pub const VERSION: &str = \"{version}\";\n\
             /// Base namespace URI.\n\
             pub const BASE_NAMESPACE: &str = \"{namespace}\";\n\
             /// Full `xsi:schemaLocation` value.\n\
             pub const SCHEMA_LOCATION: &str = \"{schema_location}\";\n\
             \n\
             /// The AUTOSAR `{version}` release descriptor.\n\
             pub fn release() -> AutosarReleaseDescriptor {{\n\
             \x20   let version =\n\
             \x20       AutosarMetaModelVersionData::create_from_canonical_version_number_string(VERSION)\n\
             \x20           .expect(\"valid AUTOSAR version\");\n\
             \x20   let mut release = AutosarReleaseDescriptor::new(RELEASE_ID.to_string(), version);\n\
             \x20   release.set_base_namespace(BASE_NAMESPACE.to_string());\n\
             \x20   release\n\
             }}\n\
             \n\
             /// `{prefix}` AUTOSAR resource factory.\n\
             pub type {prefix}ResourceFactory = AutosarResourceFactory;\n\
             \n\
             /// Create a `{prefix}` factory carrying the `{version}` release.\n\
             pub fn new_{snake}_resource_factory() -> {prefix}ResourceFactory {{\n\
             \x20   AutosarResourceFactory::new(Some(release()))\n\
             }}\n"
        )
    }

    /// The generated crate name (C++ `pkgClassPrefix`, lower-cased for Rust).
    fn crate_name(&self, model: &GenModel) -> String {
        if self.config.crate_spec.package_name.is_empty() {
            package_module_name(model.package().name())
        } else {
            self.config.crate_spec.package_name.clone()
        }
    }

    /// The generated crate's manifest: the generic runtime deps plus, when the
    /// resource glue is emitted, `artop-runtime`.
    fn manifest(&self, name: &str) -> String {
        let mut out = format!(
            "# GENERATED static-model crate (produced by artop-codegen).\n\
             # Compiled here so the model is usable without the source .ecore file.\n\
             [package]\n\
             name = \"{name}\"\n\
             version = \"0.0.0\"\n\
             edition = \"2021\"\n\
             \n\
             [workspace]\n\
             \n\
             [dependencies]\n\
             emf-common = {{ path = \"{common}\" }}\n\
             emf-ecore = {{ path = \"{ecore}\" }}\n",
            common = self.config.crate_spec.emf_common.display(),
            ecore = self.config.crate_spec.emf_ecore.display(),
        );
        if self.config.generate_resource {
            out.push_str(&format!(
                "artop-runtime = {{ path = \"{}\" }}\n",
                self.config.artop_runtime.display()
            ));
        }
        out
    }
}

/// C++ `pkgClassPrefix`: capitalize the package name for the class prefix.
fn class_prefix(package_name: &str) -> String {
    if package_name.is_empty() {
        "Unnamed".to_string()
    } else {
        struct_name(package_name)
    }
}

/// Write `content` to `path`, creating parent directories as needed (C++
/// `ArtopCppGenerator::writeFile`).
fn write_file(path: &Path, content: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("creating `{}`: {e}", parent.display()))?;
    }
    std::fs::write(path, content).map_err(|e| format!("writing `{}`: {e}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> GenModel {
        GenModel::load(include_str!(
            "../../../emf-ecore-codegen/samples/library.ecore"
        ))
        .unwrap()
    }

    #[test]
    fn config_defaults_match_cpp() {
        let cfg = ArtopGenConfig::default();
        assert_eq!(cfg.release_id, "org.artop.aal.autosar448");
        assert_eq!(cfg.version, "4.4.8");
        assert_eq!(cfg.base_namespace_uri, "http://autosar.org/schema/r4.0");
        assert_eq!(
            cfg.schema_location,
            "http://autosar.org/schema/r4.0 AUTOSAR_4-4-8.xsd"
        );
        assert!(cfg.generate_resource);
        assert!(cfg.inject_root_extensions);
        assert!(cfg.artop_runtime.ends_with("emf-artop/artop-runtime"));
    }

    #[test]
    fn generate_from_package_writes_base_and_artop_extensions() {
        let dir = std::env::temp_dir().join("artop_codegen_unit_library");
        let _ = std::fs::remove_dir_all(&dir);

        let cfg = ArtopGenConfig {
            out_dir: dir.clone(),
            ..Default::default()
        };
        ArtopGenerator::new(cfg)
            .generate_from_package(&sample())
            .unwrap();

        let lib = std::fs::read_to_string(dir.join("src/lib.rs")).unwrap();
        assert!(lib.contains("pub fn register_package"), "{lib}");
        assert!(lib.contains("pub mod resource;"), "{lib}");
        assert!(dir.join("src/resource.rs").exists());
        assert!(dir.join("src/resource_factory.rs").exists());
        assert!(dir.join("ARTOP_ROOT_EXTENSIONS.md").exists());
    }

    #[test]
    fn no_resource_skips_glue_and_manifest_dep() {
        let dir = std::env::temp_dir().join("artop_codegen_unit_nores");
        let _ = std::fs::remove_dir_all(&dir);

        let cfg = ArtopGenConfig {
            out_dir: dir.clone(),
            generate_resource: false,
            inject_root_extensions: false,
            ..Default::default()
        };
        ArtopGenerator::new(cfg)
            .generate_from_package(&sample())
            .unwrap();

        let manifest = std::fs::read_to_string(dir.join("Cargo.toml")).unwrap();
        assert!(!manifest.contains("artop-runtime"), "{manifest}");
        assert!(!dir.join("src/resource.rs").exists());
        assert!(!dir.join("ARTOP_ROOT_EXTENSIONS.md").exists());
        let lib = std::fs::read_to_string(dir.join("src/lib.rs")).unwrap();
        assert!(!lib.contains("pub mod resource;"), "{lib}");
    }
}
