//! Full AUTOSAR static-registry emitter (Rust port of
//! `tools/gen-autosar448-model.py`).
//!
//! The AUTOSAR 4.4.8 metamodel is split across two `.ecore` documents:
//!
//! * `gautosar.ecore`   — the *generic* AUTOSAR layer (`g*` base classes such as
//!   `GARObject`, `GReferrable`, `GIdentifiable`);
//! * `autosar448.ecore` — the full AUTOSAR 4.4.8 model whose base classes
//!   (`ARObject`, `Referrable`, ...) inherit the generic layer via
//!   `gautosar.ecore#//...`.
//!
//! Unlike the generic [`emf_ecore_codegen`] pipeline — which emits one struct
//! per `EClass` and, like the C++ `CppGenerator`, only handles a single package
//! level — the arxml layer needs the *whole* metamodel as plain data: 2000+
//! classes spread over ~740 subpackages, each carrying the serialization
//! metadata (`xml.name`, `xml.namePlural`, `internal-xml-sequenceOffset`, the
//! APRXML role/type element flags, `atp.Splitkey`, `ordered`, ...). Expressing
//! inheritance as data is what lets the 2105-class model compile in seconds and
//! drive ARXML read/write/reflection at runtime.
//!
//! This module walks `eSubpackages` recursively, merges both documents into one
//! flat registry and emits the same `registry.rs` the Python tool produced, so
//! the static model (and therefore ARXML read/write) is generated by the Rust
//! code generator rather than an out-of-band script — mirroring the role of the
//! C++ `ArtopCppGenerator`.
//!
//! Regenerate with
//! `artop-codegen registry <gautosar.ecore> <autosar448.ecore> <out/registry.rs>`.

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::Path;

use emf_xmi::parser::{parse, XmlNode};

/// The `ExtendedMetaData` annotation source (as written in the `.ecore`).
const EMD: &str = "http:///org/eclipse/emf/ecore/util/ExtendedMetaData";

/// Built-in EMF/ecore data types referenced by hand-written features (e.g. the
/// FeatureMap `mixed` / `extensions` slots). They have no AUTOSAR datatype
/// entry; the generated registry resolves them to `TypeRef::None` (the loader
/// treats them as opaque text).
const EMF_BUILTIN: &[&str] = &[
    "EFeatureMapEntry",
    "EStringToStringMapEntry",
    "EObject",
    "EJavaObject",
    "EString",
    "EInt",
    "EBoolean",
    "EDouble",
    "ELong",
    "EShort",
    "EByte",
    "EChar",
    "EFloat",
    "EBigInteger",
    "EBigDecimal",
    "EDate",
    "EAny",
];

/// Diagnostics returned alongside the generated source.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct RegistryStats {
    pub packages: usize,
    pub classes: usize,
    pub features: usize,
    pub enums: usize,
    pub datatypes: usize,
    /// `eType` names that could not be resolved to a known classifier
    /// (name → occurrence count). Empty for a complete metamodel.
    pub unresolved: Vec<(String, usize)>,
    /// Longest `eSuperTypes` list seen (sanity check on the inheritance graph).
    pub max_supers: usize,
}

impl RegistryStats {
    /// One-line human-readable summary (mirrors the Python tool's `stats:` line).
    pub fn summary(&self) -> String {
        let unresolved = if self.unresolved.is_empty() {
            "none".to_string()
        } else {
            self.unresolved
                .iter()
                .map(|(n, c)| format!("{n}({c})"))
                .collect::<Vec<_>>()
                .join(", ")
        };
        format!(
            "packages: {}, classes: {}, features: {}, enums: {}, datatypes: {}, max_supers: {}; unresolved eTypes: {}",
            self.packages, self.classes, self.features, self.enums, self.datatypes, self.max_supers,
            unresolved
        )
    }
}

/// A package (root or sub) with its qualified path and namespace data.
struct PackageInfo {
    name: String,
    /// Path from the document root, e.g. `genericstructure/generaltemplateclasses`.
    qualified: String,
    ns_uri: String,
    ns_prefix: String,
}

struct ClassInfo {
    name: String,
    xml_name: String,
    xml_name_plural: String,
    content_kind: String,
    qualified: String,
    package: usize,
    abstract_: bool,
    /// Raw `eSuperTypes` references as written in the `.ecore`.
    supers: Vec<String>,
    features: Vec<Feature>,
}

struct EnumInfo {
    name: String,
    qualified: String,
    package: usize,
    literals: Vec<String>,
}

struct DataTypeInfo {
    name: String,
    qualified: String,
    package: usize,
    instance_class: String,
}

struct Feature {
    name: String,
    /// `"Reference"` or `"Attribute"`.
    kind: &'static str,
    e_type: String,
    containment: bool,
    lower: i32,
    upper: i32,
    transient: bool,
    volatile_: bool,
    derived: bool,
    default_value: String,
    xml_name: String,
    xml_name_plural: String,
    xml_attribute: bool,
    text_content: bool,
    seq_offset: i32,
    role_element: bool,
    role_wrapper: bool,
    type_element: bool,
    type_wrapper: bool,
    feature_kind: String,
    ns_prefix: String,
    splitkey: String,
    ordered: bool,
}

/// Generate the full static registry from the two AUTOSAR `.ecore` documents.
pub fn generate_registry(
    gautosar: &str,
    autosar448: &str,
) -> Result<(String, RegistryStats), String> {
    let mut packages: Vec<PackageInfo> = Vec::new();
    let mut classes: Vec<ClassInfo> = Vec::new();
    let mut enums: Vec<EnumInfo> = Vec::new();
    let mut datatypes: Vec<DataTypeInfo> = Vec::new();

    for src in [gautosar, autosar448] {
        let roots = parse(src)?;
        let root = roots
            .first()
            .ok_or_else(|| "empty .ecore document".to_string())?;
        if root.local != "EPackage" {
            return Err(format!(
                "expected root <ecore:EPackage>, found <{}>",
                root.name
            ));
        }
        let name = root.attr("name").unwrap_or("").to_string();
        let tv = details(root, "TaggedValues");
        packages.push(PackageInfo {
            name,
            qualified: String::new(),
            ns_uri: attr_nonempty(root, "nsURI")
                .map(str::to_string)
                .or_else(|| nonempty(tv.get("xml.nsUri")))
                .unwrap_or_default(),
            ns_prefix: attr_nonempty(root, "nsPrefix")
                .map(str::to_string)
                .or_else(|| nonempty(tv.get("xml.nsPrefix")))
                .unwrap_or_default(),
        });
        walk_packages(
            root,
            "",
            &mut packages,
            &mut classes,
            &mut enums,
            &mut datatypes,
        );
    }

    // ---- index by simple name (the two files use disjoint class names) ----
    let class_by_name = index_by_name(classes.iter().map(|c| c.name.as_str()));
    let enum_by_name = index_by_name(enums.iter().map(|e| e.name.as_str()));
    let dt_by_name = index_by_name(datatypes.iter().map(|d| d.name.as_str()));
    let pkg_by_qual = index_by_name(packages.iter().map(|p| p.qualified.as_str()));

    for c in &mut classes {
        c.package = package_id(&pkg_by_qual, &c.qualified);
    }
    for e in &mut enums {
        e.package = package_id(&pkg_by_qual, &e.qualified);
    }
    for d in &mut datatypes {
        d.package = package_id(&pkg_by_qual, &d.qualified);
    }

    // ---- resolve supers ----
    // Preserve the declaration order of `eSuperTypes`: EMF builds
    // `eAllStructuralFeatures` by walking the supertypes in declaration order,
    // so a derived class's inherited features keep the same relative order as in
    // the C++/Java implementations. Deduplicate keeping the first occurrence (a
    // plain set would impose index order and silently reorder inherited features,
    // e.g. flipping `xml:space` before the `L` attribute).
    let mut sup_idx: Vec<Vec<usize>> = Vec::with_capacity(classes.len());
    for c in &classes {
        let self_id = class_by_name.get(c.name.as_str()).copied();
        let mut seen = std::collections::HashSet::new();
        let mut row = Vec::new();
        for s in &c.supers {
            let nm = leaf(s);
            if let Some(&i) = class_by_name.get(nm.as_str()) {
                if Some(i) != self_id && seen.insert(i) {
                    row.push(i);
                }
            }
        }
        sup_idx.push(row);
    }

    // ---- flatten features (class-qualified; ids are global) ----
    let mut feature_index: HashMap<(String, String), usize> = HashMap::new();
    let mut feat_rows: Vec<&Feature> = Vec::new();
    let mut own_ids: Vec<Vec<usize>> = Vec::with_capacity(classes.len());
    for c in &classes {
        let mut ids = Vec::new();
        for f in &c.features {
            let key = (c.name.clone(), f.name.clone());
            let fid = *feature_index.entry(key).or_insert_with(|| {
                let id = feat_rows.len();
                feat_rows.push(f);
                id
            });
            ids.push(fid);
        }
        own_ids.push(ids);
    }

    let mut unresolved: HashMap<String, usize> = HashMap::new();
    let type_of = |f: &Feature| -> String {
        let nm = leaf(&f.e_type);
        if f.kind == "Attribute" {
            if let Some(&i) = dt_by_name.get(nm.as_str()) {
                return format!("TypeRef::DataType({i})");
            }
            if let Some(&i) = enum_by_name.get(nm.as_str()) {
                return format!("TypeRef::Enum({i})");
            }
        } else if let Some(&i) = class_by_name.get(nm.as_str()) {
            return format!("TypeRef::Class({i})");
        }
        if EMF_BUILTIN.contains(&nm.as_str()) {
            return "TypeRef::None".to_string();
        }
        "TypeRef::None".to_string()
    };
    // Count unresolved eTypes separately from emission (needs a mutable map).
    for f in &feat_rows {
        let nm = leaf(&f.e_type);
        let resolved = dt_by_name.contains_key(nm.as_str())
            || enum_by_name.contains_key(nm.as_str())
            || class_by_name.contains_key(nm.as_str())
            || EMF_BUILTIN.contains(&nm.as_str());
        if !resolved {
            *unresolved.entry(nm).or_insert(0) += 1;
        }
    }

    let n = classes.len();
    let nf = feat_rows.len();
    let max_supers = sup_idx.iter().map(Vec::len).max().unwrap_or(0);

    // NAME_TO_ID / XML_NAME_TO_ID are emitted in sorted order so the generated
    // `binary_search_by` lookups are valid.
    let mut order: Vec<usize> = (0..n).collect();
    order.sort_by(|&a, &b| classes[a].name.cmp(&classes[b].name).then(a.cmp(&b)));
    let mut xml_order: Vec<usize> = (0..n).collect();
    xml_order.sort_by(|&a, &b| {
        classes[a]
            .xml_name
            .cmp(&classes[b].xml_name)
            .then(a.cmp(&b))
    });
    let mut enum_order: Vec<usize> = (0..enums.len()).collect();
    enum_order.sort_by(|&a, &b| enums[a].name.cmp(&enums[b].name).then(a.cmp(&b)));

    // ---- emit ----
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED from gautosar.ecore + autosar448.ecore — do not edit\n");
    out.push_str("// (regenerate with `artop-codegen registry <gautosar.ecore> <autosar448.ecore> <out.rs>`)\n\n");
    writeln!(out, "pub const N_PACKAGES: usize = {};", packages.len()).unwrap();
    writeln!(out, "pub const N_CLASSES: usize = {n};").unwrap();
    writeln!(out, "pub const N_FEATURES: usize = {nf};").unwrap();
    writeln!(out, "pub const N_ENUMS: usize = {};", enums.len()).unwrap();
    writeln!(out, "pub const N_DATATYPES: usize = {};", datatypes.len()).unwrap();
    out.push('\n');

    // packages
    out.push_str("#[derive(Clone, Copy, Debug)]\npub struct PackageMeta {\n    pub name: &'static str,\n    pub ns_uri: &'static str,\n    pub ns_prefix: &'static str,\n}\n");
    out.push_str("#[rustfmt::skip]\n");
    writeln!(
        out,
        "pub static PACKAGES: [PackageMeta; {}] = [",
        packages.len()
    )
    .unwrap();
    for p in &packages {
        writeln!(
            out,
            "    PackageMeta {{ name: {}, ns_uri: {}, ns_prefix: {} }},",
            rlit(&p.name),
            rlit(&p.ns_uri),
            rlit(&p.ns_prefix)
        )
        .unwrap();
    }
    out.push_str("];\n\n");

    // enums
    out.push_str("#[derive(Clone, Copy, Debug)]\npub struct EnumMeta {\n    pub name: &'static str,\n    pub package: u32,\n    pub literals: &'static [&'static str],\n}\n");
    out.push_str("#[rustfmt::skip]\n");
    writeln!(out, "pub static ENUMS: [EnumMeta; {}] = [", enums.len()).unwrap();
    for e in &enums {
        let lits = e
            .literals
            .iter()
            .map(|l| rlit(l))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(
            out,
            "    EnumMeta {{ name: {}, package: {}, literals: &[{}] }},",
            rlit(&e.name),
            e.package,
            lits
        )
        .unwrap();
    }
    out.push_str("];\n#[rustfmt::skip]\n");
    writeln!(
        out,
        "pub static ENUM_NAME_TO_ID: [(&str, u32); {}] = [",
        enums.len()
    )
    .unwrap();
    for &i in &enum_order {
        writeln!(out, "    ({}, {}),", rlit(&enums[i].name), i).unwrap();
    }
    out.push_str("];\n\n");

    // datatypes
    out.push_str("#[derive(Clone, Copy, Debug)]\npub struct DataTypeMeta {\n    pub name: &'static str,\n    pub package: u32,\n    pub instance_class: &'static str,\n}\n");
    out.push_str("#[rustfmt::skip]\n");
    writeln!(
        out,
        "pub static DATATYPES: [DataTypeMeta; {}] = [",
        datatypes.len()
    )
    .unwrap();
    for d in &datatypes {
        writeln!(
            out,
            "    DataTypeMeta {{ name: {}, package: {}, instance_class: {} }},",
            rlit(&d.name),
            d.package,
            rlit(&d.instance_class)
        )
        .unwrap();
    }
    out.push_str("];\n\n");

    // feature kind / type enums + meta
    out.push_str("/// Whether a feature is an `EAttribute` (scalar text) or an `EReference`.\n");
    out.push_str("#[derive(Clone, Copy, PartialEq, Eq, Debug)]\npub enum FeatureKind {\n    Attribute,\n    Reference,\n}\n\n");
    out.push_str("/// Resolved `eType` of a feature.\n");
    out.push_str("#[derive(Clone, Copy, PartialEq, Eq, Debug)]\npub enum TypeRef {\n    None,\n    Class(u32),\n    Enum(u32),\n    DataType(u32),\n}\n\n");
    out.push_str("/// Serialization metadata for one `EStructuralFeature`.\n#[derive(Clone, Copy, Debug)]\npub struct FeatureMeta {\n");
    for (fld, ty) in [
        ("name", "&'static str"),
        ("xml_name", "&'static str"),
        ("xml_name_plural", "&'static str"),
        ("feature_kind", "&'static str"),
        ("kind", "FeatureKind"),
        ("ty", "TypeRef"),
        ("containment", "bool"),
        ("lower", "i32"),
        ("upper", "i32"),
        ("transient", "bool"),
        ("volatile_", "bool"),
        ("derived", "bool"),
        ("xml_attribute", "bool"),
        ("ns_prefix", "&'static str"),
        ("text_content", "bool"),
        ("seq_offset", "i32"),
        ("role_element", "bool"),
        ("role_wrapper", "bool"),
        ("type_element", "bool"),
        ("type_wrapper", "bool"),
        ("default_value", "&'static str"),
        ("splitkey", "&'static str"),
        ("ordered", "bool"),
    ] {
        writeln!(out, "    pub {fld}: {ty},").unwrap();
    }
    out.push_str("}\n#[rustfmt::skip]\n");
    writeln!(out, "pub static FEATURE_META: [FeatureMeta; {nf}] = [").unwrap();
    for f in &feat_rows {
        writeln!(
            out,
            "    FeatureMeta {{ name: {}, xml_name: {}, xml_name_plural: {}, feature_kind: {}, \
             kind: FeatureKind::{}, ty: {}, containment: {}, lower: {}, upper: {}, transient: {}, \
             volatile_: {}, derived: {}, xml_attribute: {}, ns_prefix: {}, text_content: {}, seq_offset: {}, \
             role_element: {}, role_wrapper: {}, type_element: {}, type_wrapper: {}, \
             default_value: {}, splitkey: {}, ordered: {} }},",
            rlit(&f.name),
            rlit(&f.xml_name),
            rlit(&f.xml_name_plural),
            rlit(&f.feature_kind),
            f.kind,
            type_of(f),
            f.containment,
            f.lower,
            f.upper,
            f.transient,
            f.volatile_,
            f.derived,
            f.xml_attribute,
            rlit(&f.ns_prefix),
            f.text_content,
            f.seq_offset,
            f.role_element,
            f.role_wrapper,
            f.type_element,
            f.type_wrapper,
            rlit(&f.default_value),
            rlit(&f.splitkey),
            f.ordered
        )
        .unwrap();
    }
    out.push_str("];\n\n");

    // classes
    out.push_str("/// Static metadata for one `EClass`.\n#[derive(Clone, Copy, Debug)]\npub struct ClassMeta {\n    pub name: &'static str,\n    pub xml_name: &'static str,\n    pub xml_name_plural: &'static str,\n    pub abstract_: bool,\n    pub package: u32,\n    pub content_kind: &'static str,\n    pub sups: &'static [u32],\n    pub own: &'static [u32],\n}\n");
    out.push_str("#[rustfmt::skip]\n");
    writeln!(out, "pub static ECLASS: [ClassMeta; {n}] = [").unwrap();
    for (i, c) in classes.iter().enumerate() {
        let sups = format!("&[{}]", join_usize(&sup_idx[i]));
        let own = format!("&[{}]", join_usize(&own_ids[i]));
        writeln!(
            out,
            "    ClassMeta {{ name: {}, xml_name: {}, xml_name_plural: {}, abstract_: {}, \
             package: {}, content_kind: {}, sups: {}, own: {} }},",
            rlit(&c.name),
            rlit(&c.xml_name),
            rlit(&c.xml_name_plural),
            c.abstract_,
            c.package,
            rlit(&c.content_kind),
            sups,
            own
        )
        .unwrap();
    }
    out.push_str("];\n\n");

    // name index + accessors
    out.push_str("#[rustfmt::skip]\n");
    writeln!(out, "pub static NAME_TO_ID: [(&str, u32); {n}] = [").unwrap();
    for &i in &order {
        writeln!(out, "    ({}, {}),", rlit(&classes[i].name), i).unwrap();
    }
    out.push_str("];\n#[rustfmt::skip]\n");
    writeln!(out, "pub static XML_NAME_TO_ID: [(&str, u32); {n}] = [").unwrap();
    for &i in &xml_order {
        writeln!(out, "    ({}, {}),", rlit(&classes[i].xml_name), i).unwrap();
    }
    out.push_str("];\n\n");
    out.push_str("/// Look up a class id by simple ecore name (binary search).\npub fn name_to_id(name: &str) -> Option<u32> {\n    NAME_TO_ID\n        .binary_search_by(|(n, _)| n.cmp(&name))\n        .ok()\n        .map(|i| NAME_TO_ID[i].1)\n}\n\n");
    out.push_str("/// Look up a class id by arxml element name (`xml.name`).\npub fn xml_name_to_id(xml: &str) -> Option<u32> {\n    XML_NAME_TO_ID\n        .binary_search_by(|(n, _)| n.cmp(&xml))\n        .ok()\n        .map(|i| XML_NAME_TO_ID[i].1)\n}\n\n");
    out.push_str("/// Look up an enum id by name.\npub fn enum_id(name: &str) -> Option<u32> {\n    ENUM_NAME_TO_ID\n        .binary_search_by(|(n, _)| n.cmp(&name))\n        .ok()\n        .map(|i| ENUM_NAME_TO_ID[i].1)\n}\n\n");
    out.push_str("/// Enum metadata by id.\npub fn enum_meta(id: u32) -> EnumMeta { ENUMS[id as usize] }\n\n");
    out.push_str("/// Data type metadata by id.\npub fn datatype_meta(id: u32) -> DataTypeMeta { DATATYPES[id as usize] }\n");

    let mut unresolved: Vec<(String, usize)> = unresolved.into_iter().collect();
    unresolved.sort();
    let stats = RegistryStats {
        packages: packages.len(),
        classes: n,
        features: nf,
        enums: enums.len(),
        datatypes: datatypes.len(),
        unresolved,
        max_supers,
    };
    Ok((out, stats))
}

/// Read the two `.ecore` files and generate the registry from them.
pub fn generate_registry_from_files(
    gautosar: &Path,
    autosar448: &Path,
) -> Result<(String, RegistryStats), String> {
    let g = std::fs::read_to_string(gautosar)
        .map_err(|e| format!("reading `{}`: {e}", gautosar.display()))?;
    let a = std::fs::read_to_string(autosar448)
        .map_err(|e| format!("reading `{}`: {e}", autosar448.display()))?;
    generate_registry(&g, &a)
}

/// Recursively walk a package element, collecting subpackages and classifiers.
fn walk_packages(
    elem: &XmlNode,
    parent_qualified: &str,
    packages: &mut Vec<PackageInfo>,
    classes: &mut Vec<ClassInfo>,
    enums: &mut Vec<EnumInfo>,
    datatypes: &mut Vec<DataTypeInfo>,
) {
    for ch in &elem.children {
        match ch.local.as_str() {
            "eSubpackages" => {
                let name = ch.attr("name").unwrap_or("").to_string();
                let qualified = qualify(parent_qualified, &name);
                let tv = details(ch, "TaggedValues");
                packages.push(PackageInfo {
                    name,
                    qualified: qualified.clone(),
                    ns_uri: attr_nonempty(ch, "nsURI")
                        .map(str::to_string)
                        .or_else(|| nonempty(tv.get("xml.nsUri")))
                        .unwrap_or_default(),
                    ns_prefix: attr_nonempty(ch, "nsPrefix")
                        .map(str::to_string)
                        .or_else(|| nonempty(tv.get("xml.nsPrefix")))
                        .unwrap_or_default(),
                });
                walk_packages(ch, &qualified, packages, classes, enums, datatypes);
            }
            "eClassifiers" => {
                let xt = ch.attr("xsi:type").unwrap_or("");
                let name = ch.attr("name").unwrap_or("").to_string();
                let qualified = qualify(parent_qualified, &name);
                match xt {
                    "ecore:EClass" => {
                        let tv = details(ch, "TaggedValues");
                        let emd = details(ch, EMD);
                        let xml_name = nonempty(tv.get("xml.name")).unwrap_or_else(|| name.clone());
                        let xml_name_plural =
                            nonempty(tv.get("xml.namePlural")).unwrap_or_else(|| xml_name.clone());
                        let mut supers: Vec<String> = ch
                            .attr("eSuperTypes")
                            .unwrap_or("")
                            .split_whitespace()
                            .map(str::to_string)
                            .collect();
                        for cc in &ch.children {
                            if cc.local == "eSuperTypes" {
                                let s = cc.attr("href").or_else(|| cc.attr("eType")).unwrap_or("");
                                if !s.is_empty() {
                                    supers.push(s.to_string());
                                }
                            }
                        }
                        let mut c = ClassInfo {
                            name,
                            xml_name,
                            xml_name_plural,
                            content_kind: emd.get("kind").cloned().unwrap_or_default(),
                            qualified,
                            package: 0,
                            abstract_: parse_bool(ch.attr("abstract").unwrap_or("")),
                            supers,
                            features: Vec::new(),
                        };
                        for cc in &ch.children {
                            if cc.local == "eStructuralFeatures" {
                                c.features.push(parse_feature(cc));
                            }
                        }
                        classes.push(c);
                    }
                    "ecore:EEnum" => {
                        let literals = ch
                            .children
                            .iter()
                            .filter(|cc| cc.local == "eLiterals")
                            .map(|cc| cc.attr("name").unwrap_or("").to_string())
                            .collect();
                        enums.push(EnumInfo {
                            name,
                            qualified,
                            package: 0,
                            literals,
                        });
                    }
                    "ecore:EDataType" => {
                        datatypes.push(DataTypeInfo {
                            name,
                            qualified,
                            package: 0,
                            instance_class: ch.attr("instanceClassName").unwrap_or("").to_string(),
                        });
                    }
                    _ => {}
                }
            }
            _ => {}
        }
    }
}

/// Parse one `<eStructuralFeatures>` element into a [`Feature`].
fn parse_feature(el: &XmlNode) -> Feature {
    let t = el.attr("xsi:type").unwrap_or("");
    let kind = if t == "ecore:EReference" {
        "Reference"
    } else {
        "Attribute"
    };
    let mut e_type = el.attr("eType").unwrap_or("").to_string();
    for c in &el.children {
        if c.local == "eType" {
            e_type = c
                .attr("href")
                .or_else(|| c.attr("eType"))
                .unwrap_or(&e_type)
                .to_string();
        }
    }

    let tv = details(el, "TaggedValues");
    let emd = details(el, EMD);
    let mut xml_name = tv.get("xml.name").cloned().unwrap_or_default();
    let mut xml_name_plural = tv.get("xml.namePlural").cloned().unwrap_or_default();
    let name = el.attr("name").unwrap_or("").to_string();
    if xml_name.is_empty() {
        xml_name = name.clone();
    }
    if xml_name_plural.is_empty() {
        xml_name_plural = xml_name.clone();
    }

    let seq_raw = match nonempty(tv.get("internal-xml-sequenceOffset")) {
        Some(v) if v != "null" => v,
        _ => tv.get("xml.sequenceOffset").cloned().unwrap_or_default(),
    };

    Feature {
        name,
        kind,
        e_type,
        containment: parse_bool(el.attr("containment").unwrap_or("")),
        lower: el.attr("lowerBound").map(parse_int).unwrap_or(0),
        upper: el.attr("upperBound").map(parse_int).unwrap_or(1),
        transient: parse_bool(el.attr("transient").unwrap_or("")),
        volatile_: parse_bool(el.attr("volatile").unwrap_or("")),
        derived: parse_bool(el.attr("derived").unwrap_or("")),
        default_value: el.attr("defaultValueLiteral").unwrap_or("").to_string(),
        xml_name,
        xml_name_plural,
        xml_attribute: parse_bool(tv.get("xml.attribute").map(String::as_str).unwrap_or("")),
        text_content: parse_bool(tv.get("xml.text").map(String::as_str).unwrap_or("")),
        seq_offset: parse_int(&seq_raw),
        role_element: parse_bool(tv.get("xml.roleElement").map(String::as_str).unwrap_or("")),
        role_wrapper: parse_bool(
            tv.get("xml.roleWrapperElement")
                .map(String::as_str)
                .unwrap_or(""),
        ),
        type_element: parse_bool(tv.get("xml.typeElement").map(String::as_str).unwrap_or("")),
        type_wrapper: parse_bool(
            tv.get("xml.typeWrapperElement")
                .map(String::as_str)
                .unwrap_or(""),
        ),
        feature_kind: emd.get("kind").cloned().unwrap_or_default(),
        ns_prefix: tv.get("xml.nsPrefix").cloned().unwrap_or_default(),
        // `atp.Splitkey` (TaggedValues) drives child ordering for unordered
        // features; `ordered` (ExtendedMetaData) defaults to true when absent,
        // matching the C++ `isFeatureOrdered`.
        splitkey: tv.get("atp.Splitkey").cloned().unwrap_or_default(),
        ordered: nonempty(emd.get("ordered")).unwrap_or_else(|| "true".to_string()) != "false",
    }
}

/// Details of the `<eAnnotations>` child with the given `source` (empty if absent).
fn details(elem: &XmlNode, source: &str) -> HashMap<String, String> {
    for a in &elem.children {
        if a.local == "eAnnotations" && a.attr("source") == Some(source) {
            let mut d = HashMap::new();
            for dd in &a.children {
                if dd.local == "details" {
                    d.insert(
                        dd.attr("key").unwrap_or("").to_string(),
                        dd.attr("value").unwrap_or("").to_string(),
                    );
                }
            }
            return d;
        }
    }
    HashMap::new()
}

/// Last path segment of an ecore reference (`#//a/b/C` or `file#//a/b/C` → `C`).
fn leaf(reference: &str) -> String {
    let after = match reference.rfind("#//") {
        Some(i) => &reference[i + 3..],
        None => reference,
    };
    after.rsplit('/').next().unwrap_or("").trim().to_string()
}

fn parse_bool(s: &str) -> bool {
    matches!(s, "true" | "1" | "True" | "TRUE")
}

fn parse_int(s: &str) -> i32 {
    if s.is_empty() {
        return 0;
    }
    s.trim().parse().unwrap_or(0)
}

/// `Some(v)` when `v` is present and non-empty (Python's `x or default`).
fn nonempty(v: Option<&String>) -> Option<String> {
    v.filter(|s| !s.is_empty()).cloned()
}

/// `Some(v)` when the attribute is present and non-empty (Python's `x or ...`).
fn attr_nonempty<'a>(node: &'a XmlNode, name: &str) -> Option<&'a str> {
    node.attr(name).filter(|s| !s.is_empty())
}

fn qualify(parent: &str, name: &str) -> String {
    if parent.is_empty() {
        name.to_string()
    } else {
        format!("{parent}/{name}")
    }
}

/// Index items by simple name, keeping the first occurrence (Python `setdefault`).
fn index_by_name<'a>(names: impl Iterator<Item = &'a str>) -> HashMap<String, usize> {
    let mut map = HashMap::new();
    for (i, n) in names.enumerate() {
        map.entry(n.to_string()).or_insert(i);
    }
    map
}

/// Package id of the owning package of a qualified classifier path.
fn package_id(pkg_by_qual: &HashMap<String, usize>, qualified: &str) -> usize {
    let owner = qualified.rsplit_once('/').map(|(p, _)| p).unwrap_or("");
    pkg_by_qual.get(owner).copied().unwrap_or(0)
}

fn join_usize(xs: &[usize]) -> String {
    xs.iter()
        .map(|x| x.to_string())
        .collect::<Vec<_>>()
        .join(",")
}

/// Escape a Rust string literal body (Python `rlit`).
fn rlit(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A minimal two-document metamodel exercising subpackages, cross-package
    /// inheritance and the ARXML serialization metadata.
    const GENERIC: &str = r##"<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="gautosar" nsURI="http://autosar.org/schema/r4.0/gautosar" nsPrefix="gautosar">
  <eSubpackages name="generic" nsURI="http://autosar.org/schema/r4.0/gautosar/generic" nsPrefix="">
    <eClassifiers xsi:type="ecore:EClass" name="GReferrable" abstract="true">
      <eAnnotations source="TaggedValues">
        <details key="xml.name" value="G-REFERRABLE"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortName" eType="#//generic/ShortName">
        <eAnnotations source="TaggedValues">
          <details key="xml.name" value="SHORT-NAME"/>
          <details key="internal-xml-sequenceOffset" value="1"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="ShortName" instanceClassName="java.lang.String"/>
  </eSubpackages>
</ecore:EPackage>"##;

    const AUTOSAR: &str = r##"<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="autosar40" nsURI="http://autosar.org/schema/r4.0" nsPrefix="">
  <eSubpackages name="genericstructure" nsURI="http://autosar.org/schema/r4.0/autosar40/gs" nsPrefix="">
    <eSubpackages name="identifiable" nsURI="" nsPrefix="">
      <eClassifiers xsi:type="ecore:EClass" name="Referrable"
          eSuperTypes="#//generic/generic/GReferrable">
        <eAnnotations source="TaggedValues">
          <details key="xml.name" value="REFERRABLE"/>
          <details key="internal-xml-sequenceOffset" value="1"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="referrable"
            eType="#//genericstructure/identifiable/Referrable" containment="true" upperBound="-1">
          <eAnnotations source="TaggedValues">
            <details key="xml.name" value="REFERRABLE"/>
            <details key="xml.namePlural" value="REFERRABLES"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="Color">
        <eLiterals name="RED"/>
        <eLiterals name="GREEN"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>"##;

    #[test]
    fn walks_subpackages_and_qualifies_them() {
        let (src, stats) = generate_registry(GENERIC, AUTOSAR).unwrap();
        // 2 roots + generic + genericstructure + identifiable = 5.
        assert_eq!(stats.packages, 5, "{src}");
        // GReferrable + Referrable.
        assert_eq!(stats.classes, 2);
        assert_eq!(stats.features, 2);
        assert_eq!(stats.enums, 1);
        assert_eq!(stats.datatypes, 1);
        assert!(stats.unresolved.is_empty(), "{:?}", stats.unresolved);
    }

    #[test]
    fn resolves_cross_package_inheritance_and_types() {
        let (src, _) = generate_registry(GENERIC, AUTOSAR).unwrap();
        // `Referrable` inherits `GReferrable` (cross-document, cross-package).
        assert!(src.contains("sups: &[0]"), "{src}");
        // Attribute `shortName` resolves to the ShortName data type (id 0).
        assert!(src.contains("TypeRef::DataType(0)"), "{src}");
        // Containment reference resolves to the Referrable class (id 1).
        assert!(src.contains("TypeRef::Class(1)"), "{src}");
    }

    #[test]
    fn carries_arxml_serialization_metadata() {
        let (src, _) = generate_registry(GENERIC, AUTOSAR).unwrap();
        assert!(src.contains("xml_name: \"SHORT-NAME\""), "{src}");
        assert!(src.contains("xml_name_plural: \"REFERRABLES\""), "{src}");
        assert!(src.contains("seq_offset: 1"), "{src}");
        assert!(src.contains("content_kind: \"element\""), "{src}");
    }

    #[test]
    fn emits_sorted_lookup_tables() {
        let (src, _) = generate_registry(GENERIC, AUTOSAR).unwrap();
        // NAME_TO_ID sorted by ecore name: GReferrable (0) before Referrable (1).
        let name_idx = src.find("NAME_TO_ID").unwrap();
        let table = &src[name_idx..];
        let g = table.find("(\"GReferrable\"").unwrap();
        let r = table.find("(\"Referrable\"").unwrap();
        assert!(g < r, "{table}");
    }

    #[test]
    fn rejects_non_ecore_root() {
        let err = generate_registry("<foo/>", GENERIC).unwrap_err();
        assert!(err.contains("expected root"), "{err}");
    }
}
